name: Discord Notification
on:
  push:
    branches:
      - main

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install discord.js

      - name: Run Discord Notification Script
        run: |
          node -e "const { Client } = require('discord.js');
          const client = new Client();
          
          client.once('ready', () => {
              console.log('Bot is ready!');
          });
          
          client.login(process.env.BOT_KEY);
          
          client.on('message', async message => {
              if (message.content === '!watchCommits') {
                  message.channel.send('Ich werde jetzt Commits überwachen.');
              }
          });
          
          client.on('commit', async (commit) => {
              const channel = client.channels.cache.find(ch => ch.name === 'rocketscience');
              channel.send(`Es wurde ein neuer Commit gemacht`);
          });"
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
