name: Discord Notification on Commit

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install discord.py==1.7.3

      - name: Send Discord notification
        run: python send_discord_message.py
        env:
          DISCORD_TOKEN: ${{ secrets.BOT_KEY }}

