name: Discord Notification
on:
  push:
    branches:
      - main

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install discord.js

      - name: Run Discord Notification Script
        run: node .github/workflows/discord-notification-script.js
        env:
          BOT_KEY: ${{ secrets.BOT_KEY }}
